# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
version: 1
title: philcrissman
email: phil.crissman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to put things
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://philcrissman.net" # the base hostname & protocol for your site
twitter_username: philcrissman
github_username:  philcrissman
simple_search: http://google.com/search

# Build settings
markdown: kramdown
kramdown:  
  input: GFM
  syntax_highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
# permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
